using System.Text;

namespace AtomUI.City.Generators.DependencyInjection;

public static class ServiceRegistrarSourceBuilder
{
    public static string GetRegistrarTypeName(string assemblyName)
    {
        var identifier = new StringBuilder();
        foreach (var character in assemblyName)
        {
            identifier.Append(char.IsLetterOrDigit(character) || character == '_' ? character : '_');
        }

        if (identifier.Length == 0 || char.IsDigit(identifier[0]))
        {
            identifier.Insert(0, '_');
        }

        return $"AtomUI.City.Generated.GeneratedServiceRegistrar_{identifier}_{ComputeHash(assemblyName):X8}";
    }

    public static string Build(
        string assemblyName,
        string? ownerModuleTypeName,
        IReadOnlyList<ServiceRegistrationMetadata> registrations,
        IReadOnlyList<string> referencedRegistrarTypeNames)
    {
        var typeName = GetRegistrarTypeName(assemblyName);
        var separator = typeName.LastIndexOf('.');
        var ns = typeName.Substring(0, separator);
        var name = typeName.Substring(separator + 1);
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.Append("[assembly: global::AtomUI.City.Core.DependencyInjection.GeneratedServiceManifestAttribute(typeof(global::")
            .Append(typeName).AppendLine("))]");
        builder.AppendLine();
        builder.Append("namespace ").Append(ns).AppendLine(";");
        builder.AppendLine();
        builder.Append("public sealed class ").Append(name)
            .AppendLine(" : global::AtomUI.City.Core.DependencyInjection.IServiceRegistrar");
        builder.AppendLine("{");

        for (var index = 0; index < registrations.Count; index++)
        {
            if (registrations[index].ExposedServiceTypeNames.Count > 1)
            {
                builder.Append("    private static readonly object BackingKey")
                    .Append(index).AppendLine(" = new object();");
            }
        }

        builder.AppendLine("    public void Register(global::AtomUI.City.Core.DependencyInjection.IServiceRegistrarContext context)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");

        foreach (var referencedRegistrar in referencedRegistrarTypeNames.Distinct(StringComparer.Ordinal).OrderBy(value => value, StringComparer.Ordinal))
        {
            builder.Append("        context.RegisterRegistrar(typeof(global::").Append(referencedRegistrar)
                .Append("), static () => new global::").Append(referencedRegistrar).AppendLine("());");
        }

        if (registrations.Count > 0 && ownerModuleTypeName is not null)
        {
            builder.Append("        context.Register(typeof(global::").Append(ownerModuleTypeName)
                .AppendLine("), static services =>");
            builder.AppendLine("        {");

            for (var index = 0; index < registrations.Count; index++)
            {
                AppendRegistration(builder, registrations[index], index);
            }

            builder.AppendLine("        });");
        }

        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private static void Apply(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor descriptor, bool replace, bool tryAdd)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (replace) global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.Replace(services, descriptor);");
        builder.AppendLine("        else if (tryAdd) global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAdd(services, descriptor);");
        builder.AppendLine("        else");
        builder.AppendLine("        {");
        builder.AppendLine("            foreach (var existing in services)");
        builder.AppendLine("            {");
        builder.AppendLine("                if (existing.ServiceType == descriptor.ServiceType && existing.IsKeyedService == descriptor.IsKeyedService && (!descriptor.IsKeyedService || global::System.Object.Equals(existing.ServiceKey, descriptor.ServiceKey)))");
        builder.AppendLine("                    throw new global::System.InvalidOperationException($\"Generated service '{descriptor.ServiceType.FullName}' has already been registered for the same key. Use Replace or TryAdd to declare the conflict policy.\");");
        builder.AppendLine("            }");
        builder.AppendLine("            services.Add(descriptor);");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendRegistration(StringBuilder builder, ServiceRegistrationMetadata registration, int index)
    {
        var lifetime = "global::Microsoft.Extensions.DependencyInjection.ServiceLifetime." + registration.Lifetime;
        var implementation = "typeof(global::" + registration.ImplementationTypeName + ")";

        if (registration.ExposedServiceTypeNames.Count == 1)
        {
            AppendDescriptor(builder, registration, registration.ExposedServiceTypeNames[0], implementation, lifetime, null);
            return;
        }

        builder.Append("            services.Add(global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.DescribeKeyed(")
            .Append(implementation).Append(", BackingKey").Append(index).Append(", ")
            .Append(implementation).Append(", ").Append(lifetime).AppendLine("));");

        foreach (var exposed in registration.ExposedServiceTypeNames)
        {
            AppendDescriptor(builder, registration, exposed, implementation, lifetime, index);
        }
    }

    private static void AppendDescriptor(StringBuilder builder, ServiceRegistrationMetadata registration, string exposed, string implementation, string lifetime, int? backingIndex)
    {
        builder.Append("            Apply(services, ");
        if (backingIndex is null)
        {
            if (registration.Key is null)
            {
                builder.Append("global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(typeof(global::")
                    .Append(exposed).Append("), ").Append(implementation).Append(", ").Append(lifetime).Append(')');
            }
            else
            {
                builder.Append("global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.DescribeKeyed(typeof(global::")
                    .Append(exposed).Append("), ").Append(ToLiteral(registration.Key)).Append(", ")
                    .Append(implementation).Append(", ").Append(lifetime).Append(')');
            }
        }
        else if (registration.Key is null)
        {
            builder.Append("global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(typeof(global::")
                .Append(exposed).Append("), static provider => global::Microsoft.Extensions.DependencyInjection.ServiceProviderKeyedServiceExtensions.GetRequiredKeyedService<global::")
                .Append(registration.ImplementationTypeName).Append(">(provider, BackingKey").Append(backingIndex.Value)
                .Append("), ").Append(lifetime).Append(')');
        }
        else
        {
            builder.Append("global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.DescribeKeyed(typeof(global::")
                .Append(exposed).Append("), ").Append(ToLiteral(registration.Key))
                .Append(", static (provider, _) => global::Microsoft.Extensions.DependencyInjection.ServiceProviderKeyedServiceExtensions.GetRequiredKeyedService<global::")
                .Append(registration.ImplementationTypeName).Append(">(provider, BackingKey").Append(backingIndex.Value)
                .Append("), ").Append(lifetime).Append(')');
        }

        builder.Append(", ").Append(registration.Replace ? "true" : "false")
            .Append(", ").Append(registration.TryAdd ? "true" : "false").AppendLine(");");
    }

    private static string ToLiteral(string value) => "@\"" + value.Replace("\"", "\"\"") + "\"";

    private static uint ComputeHash(string value)
    {
        var hash = 2166136261u;
        foreach (var character in value)
        {
            hash ^= character;
            hash *= 16777619;
        }
        return hash;
    }
}
