<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Grpc.Core.Api" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
    <PackageReference Include="Microsoft.Extensions.Http" />

    <ProjectReference Include="../AtomUI.City.Core/AtomUI.City.Core.csproj" />
    <ProjectReference Include="../AtomUI.City.Security/AtomUI.City.Security.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFrameworks>$(AtomUICityTargetFrameworks)</TargetFrameworks>
  </PropertyGroup>

</Project>
